name: fitbitter_example
description: A simple app that demonstrates the use of fitbitter.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ------- FITBITTER 
  fitbitter:
    path: ../
  # --------------------

  # ----- PROVIDER
  provider: ^6.1.1
  # -----

  flutter_lints: ^3.0.1

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

